#https://github.com/irfan1pathan/demo-windows-docker/blob/main/dokerdemo/Dockerfile
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build-env

# https://docs.microsoft.com/en-us/dotnet/architecture/containerized-lifecycle/design-develop-containerized-apps/set-up-windows-containers-with-powershell
# RUN powershell add-windowsfeature web-asp-net45

WORKDIR /app