
name: "docker CI workflow"

on:
  push:
    branches: [ main ]



jobs:
         
  windows-2022:
    name: "windows 2022"  
    runs-on: windows-2022
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: "check if server is virtual"
      run: Systeminfo | findstr /i model   
    - name: "check the PROCESSOR_ARCHITECTURE environment variable.64-bit systems will say AMD64 and 32-bit systems should say x86"
      run: wmic OS get OSArchitecture     
    - name: "osfingerprinting"
      run: systeminfo | more  
    - name: "display all processes, executable path"
      run: wmic process list full         
    - name: "list of running services"
      run: tasklist         
    - name: "list of all processes along with their corresponding PID, and services that are tied to them"
      run: tasklist /svc  
    - name: "look for unusual services"
      run: net start                       
    - name: "query unusual services"
      run: sc query  
      # https://hub.docker.com/_/microsoft-windows-base-os-images
      # Windows container version compatibility
      # https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility?tabs=windows-server-2022%2Cwindows-10-21H1
    - name: "docker info"
      run: |
        docker info
        docker version
        docker --version
        docker ps
    - name: "Deploy a Test Container"
      run: |
        docker pull mcr.microsoft.com/windows/nanoserver:ltsc2022
        docker images   

  windows-latest:
    name: "windows-latest"  
    runs-on: windows-latest
    env:
      distribution: "scientificlinux" # https://hub.docker.com/_/sl
      version: "latest"
      name: "servercore/base"
      # dockerfilename: "Dockerfile.iis"    
      dockerfilename: "Dockerfile.servercore.2019"    
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: "check if server is virtual"
      run: Systeminfo | findstr /i model   
    - name: "check the PROCESSOR_ARCHITECTURE environment variable.64-bit systems will say AMD64 and 32-bit systems should say x86"
      run: wmic OS get OSArchitecture     
    - name: "osfingerprinting"
      run: systeminfo | more  
    - name: "display all processes, executable path"
      run: wmic process list full         
    - name: "list of running services"
      run: tasklist         
    - name: "list of all processes along with their corresponding PID, and services that are tied to them"
      run: tasklist /svc  
    - name: "look for unusual services"
      run: net start                       
    - name: "query unusual services"
      run: sc query  
      # https://hub.docker.com/_/microsoft-windows-base-os-images
      # Windows container version compatibility
      # https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility?tabs=windows-server-2022%2Cwindows-10-21H1
    - name: "docker info"
      run: |
        # docker info
        # docker version
        docker --version
        # docker ps
    - name: "Deploy a Test Container"
      run: |
        docker run --name dock2019 mcr.microsoft.com/windows/nanoserver:1809
        docker images
    - name: "build docker image"
      run: |
        # echo $env:dockerfilename 
        # echo $env:name     
        docker build --no-cache --rm  -t $env:name/$env:version  . --file dockerfiles/$env:dockerfilename
        docker image ls
        # docker image history ${name}/${version}
        # docker system df -v               
        # # docker image inspect ${name}/${version}
    - name: "build docker dotnet image"
      run: |  
        docker build --no-cache --rm  -t dotnet/base/latest  . --file dockerfiles/Dockerfile.dotnet
        docker image ls