
name: "matrix servercore 2022 docker CI workflow"

on:
  push:
    branches: [ test ]



jobs:
         
  # windows-2022: #The container operating system does not match the host operating system.
  windows-2022: 
    name: "windows 2022 amd64"  
    runs-on: windows-2022    
    strategy:
      matrix:
        node:
        #  - apache
        #  - chocolatey       
        #  - iis
         - msopenjdk
        #  - sysinternals
    env:
      distro: "srvcore2022"        
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: "check if server is virtual"
      run: Systeminfo | findstr /i model   
    - name: "check the PROCESSOR_ARCHITECTURE environment variable.64-bit systems will say AMD64 and 32-bit systems should say x86"
      run: wmic OS get OSArchitecture     
    - name: "osfingerprinting"
      run: systeminfo | more  
    - name: "display all processes, executable path"
      run: wmic process list full         
    - name: "list of running services"
      run: tasklist         
    - name: "list of all processes along with their corresponding PID, and services that are tied to them"
      run: tasklist /svc  
    - name: "look for unusual services"
      run: net start                       
    - name: "query unusual services"
      run: sc query  
      # https://hub.docker.com/_/microsoft-windows-base-os-images
      # Windows container version compatibility
      # https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility?tabs=windows-server-2022%2Cwindows-10-21H1
    - name: "docker info"
      run: |
        docker info
        docker version
        docker --version
        docker ps
    - name: "run docker matrix build test"  
      run: |
        $curDir = Get-Location
        Write-Host "Current Working Directory: $curDir"
        cd $curDir/dockerfiles/servercore/2022/amd64        
        cd ${{matrix.node}}
        docker build -t srvcore2022/${{matrix.node}} .
        docker image ls 
        # docker image history srvcore2022/${{matrix.node}}
        # docker system df -v               
        # docker image inspect srvcore2022/${{matrix.node}}  
        docker run srvcore2022/msopenjdk:latest     
        docker ps -a
        # docker container exec -it javatest powershell     

  # # windows-2022: #The container operating system does not match the host operating system.
  # windows-2022-amd64: 
  #   name: "windows 2022 amd64"  
  #   runs-on: windows-2022    
  #   strategy:
  #     matrix:
  #       node:
  #       #  - apache
  #       #  - chocolatey       
  #        - iis
  #       #  - sysinternals
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v1
  #   - name: "check if server is virtual"
  #     run: Systeminfo | findstr /i model   
  #   - name: "check the PROCESSOR_ARCHITECTURE environment variable.64-bit systems will say AMD64 and 32-bit systems should say x86"
  #     run: wmic OS get OSArchitecture     
  #   - name: "osfingerprinting"
  #     run: systeminfo | more  
  #   - name: "display all processes, executable path"
  #     run: wmic process list full         
  #   - name: "list of running services"
  #     run: tasklist         
  #   - name: "list of all processes along with their corresponding PID, and services that are tied to them"
  #     run: tasklist /svc  
  #   - name: "look for unusual services"
  #     run: net start                       
  #   - name: "query unusual services"
  #     run: sc query  
  #     # https://hub.docker.com/_/microsoft-windows-base-os-images
  #     # Windows container version compatibility
  #     # https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility?tabs=windows-server-2022%2Cwindows-10-21H1
  #   - name: "docker info"
  #     run: |
  #       docker info
  #       docker version
  #       docker --version
  #       docker ps
  #   - name: "run docker matrix build test"
  #     run: |
  #       $curDir = Get-Location
  #       Write-Host "Current Working Directory: $curDir"
  #       cd $curDir/dockerfiles/servercore/2022        
  #       cd ${{matrix.node}}
  #       docker build -t srvcore2022/${{matrix.node}} .
  #       docker image ls 
  #       docker image history srvcore2022/${{matrix.node}}
  #       docker system df -v               
  #       docker image inspect srvcore2022/${{matrix.node}}                
